# Generated by Django 5.2.17 on 2026-10-04 20:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('source_hash', models.CharField(max_length=64)),
                ('source_text', models.TextField(max_length=8000)),
                ('target_language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('pt', 'Português'), ('ar', 'العربية'), ('sw', 'Kiswahili')], max_length=5)),
                ('mode', models.CharField(choices=[('translate', 'Traduire'), ('simplify', 'Vulgariser')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'En cours'), ('ready', 'Prête'), ('failed', 'Échec')], default='pending', max_length=10)),
                ('result', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_hash', 'target_language', 'mode'), name='translation_unique')],
            },
        ),
    ]
