# Generated by Django 5.2.17 on 2026-10-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='target_language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('pt', 'Português'), ('ar', 'العربية'), ('sw', 'Kiswahili'), ('wo', 'Wolof (Sénégal)'), ('bm', 'Bambara / Bamanankan (Mali)'), ('dyu', "Dioula / Julakan (Côte d'Ivoire, Burkina Faso)"), ('mos', 'Mooré / Mòoré (Burkina Faso)'), ('ha', 'Hausa'), ('yo', 'Yorùbá (avec les tons)'), ('ig', 'Igbo'), ('ln', 'Lingala'), ('rw', 'Kinyarwanda'), ('am', 'Amharique (አማርኛ, écriture guèze)'), ('zu', 'isiZulu')], max_length=5),
        ),
    ]
