# Generated by Django 5.2.17 on 2026-10-04 20:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('target_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Commentaire'), ('question', 'Question'), ('answer', 'Réponse')], max_length=20)),
                ('target_id', models.UUIDField()),
                ('reason', models.CharField(choices=[('spam', 'Spam ou publicité'), ('abuse', 'Harcèlement ou propos haineux'), ('scam', 'Arnaque'), ('secret', 'Donnée sensible exposée'), ('off_topic', 'Hors sujet'), ('other', 'Autre')], max_length=20)),
                ('details', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('open', 'À traiter'), ('hidden', 'Contenu masqué'), ('dismissed', 'Rejeté')], default='open', max_length=10)),
                ('ai_verdict', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='moderation__target__dc17d8_idx'), models.Index(fields=['status'], name='moderation__status_3fc7e7_idx')],
            },
        ),
    ]
