# Generated by Django 5.2.17 on 2026-10-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_totp_enabled_at_user_totp_last_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('google', 'Google')], max_length=20),
        ),
    ]
