# Generated by Django 5.2.17 on 2026-10-04 20:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=120)),
                ('language', models.CharField(max_length=40)),
                ('content', models.TextField(max_length=50000)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('ai_review', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SnippetVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('content', models.TextField()),
                ('number', models.PositiveIntegerField()),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='snippets.snippet')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.AddIndex(
            model_name='snippet',
            index=models.Index(fields=['owner', '-created_at'], name='snippets_sn_owner_i_393d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='snippet',
            index=models.Index(fields=['is_public', '-published_at'], name='snippets_sn_is_publ_c84875_idx'),
        ),
        migrations.AddConstraint(
            model_name='snippetversion',
            constraint=models.UniqueConstraint(fields=('snippet', 'number'), name='snippets_version_unique'),
        ),
    ]
