# Generated by Django 5.2.17 on 2026-10-04 20:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingGuide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('repo_url', models.URLField()),
                ('project_id', models.UUIDField(blank=True, null=True)),
                ('commit_sha', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('pending', 'En cours'), ('ready', 'Prêt'), ('failed', 'Échec')], default='pending', max_length=10)),
                ('content', models.TextField(blank=True)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_guides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['repo_url', '-created_at'], name='onboarding__repo_ur_f02763_idx')],
            },
        ),
    ]
