# Generated by Django 5.2.17 on 2026-10-06 17:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_private', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookmarkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('post_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('snippet_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('question_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookmarks.bookmarkcollection')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='bookmarkcollection',
            index=models.Index(fields=['owner', '-created_at'], name='bookmarks_b_owner_i_da379f_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookmarkcollection',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('owner', 'name'), name='bookmarks_collection_unique_name'),
        ),
        migrations.AddConstraint(
            model_name='bookmarkitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('post_id__isnull', False), ('question_id__isnull', True), ('snippet_id__isnull', True)), models.Q(('post_id__isnull', True), ('question_id__isnull', True), ('snippet_id__isnull', False)), models.Q(('post_id__isnull', True), ('question_id__isnull', False), ('snippet_id__isnull', True)), _connector='OR'), name='bookmarks_item_one_target'),
        ),
        migrations.AddConstraint(
            model_name='bookmarkitem',
            constraint=models.UniqueConstraint(condition=models.Q(('post_id__isnull', False)), fields=('collection', 'post_id'), name='bookmarks_item_unique_post_id'),
        ),
        migrations.AddConstraint(
            model_name='bookmarkitem',
            constraint=models.UniqueConstraint(condition=models.Q(('snippet_id__isnull', False)), fields=('collection', 'snippet_id'), name='bookmarks_item_unique_snippet_id'),
        ),
        migrations.AddConstraint(
            model_name='bookmarkitem',
            constraint=models.UniqueConstraint(condition=models.Q(('question_id__isnull', False)), fields=('collection', 'question_id'), name='bookmarks_item_unique_question_id'),
        ),
    ]
