# Generated by Django 5.2.17 on 2026-10-06 17:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('meetup', 'Meetup'), ('hackathon', 'Hackathon'), ('webinar', 'Webinar'), ('conference', 'Conférence'), ('atelier', 'Atelier')], max_length=12)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('country', models.CharField(blank=True, db_index=True, max_length=60)),
                ('is_online', models.BooleanField(default=False)),
                ('organizer', models.CharField(max_length=100)),
                ('registration_url', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True, max_length=6000)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=120)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, db_index=True, max_length=60)),
                ('is_remote', models.BooleanField(default=False)),
                ('contract_type', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('freelance', 'Freelance'), ('stage', 'Stage'), ('alternance', 'Alternance'), ('temps_partiel', 'Temps partiel')], max_length=15)),
                ('description', models.TextField(max_length=6000)),
                ('apply_url', models.CharField(max_length=300)),
                ('stack', models.JSONField(blank=True, default=list)),
                ('salary_range', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='jobs_events_is_acti_9cda01_idx')],
            },
        ),
    ]
