# Generated by Django 5.2.17 on 2026-10-04 20:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('token', models.CharField(max_length=200, unique=True)),
                ('platform', models.CharField(blank=True, max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(choices=[('new_comment', 'Nouveau commentaire'), ('comment_reply', 'Réponse à un commentaire'), ('post_liked', 'Post aimé'), ('new_answer', 'Nouvelle réponse'), ('answer_accepted', 'Réponse acceptée'), ('ai_answer_ready', 'Réponse IA prête'), ('snippet_flagged', 'Snippet retiré'), ('content_hidden', 'Contenu masqué'), ('guide_ready', "Guide d'onboarding prêt"), ('application_received', 'Nouvelle candidature'), ('application_answered', 'Réponse à une candidature')], max_length=30)),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(blank=True, max_length=300)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='notificatio_recipie_ce9d56_idx')],
            },
        ),
    ]
