# Generated by Django 5.2.17 on 2026-10-04 20:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('bio', models.TextField(blank=True, max_length=600)),
                ('avatar_url', models.URLField(blank=True)),
                ('stack', models.JSONField(blank=True, default=list)),
                ('github_username', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=80)),
                ('website', models.URLField(blank=True)),
                ('open_to_work', models.BooleanField(default=False)),
                ('ai_bio_suggestion', models.TextField(blank=True)),
                ('ai_bio_status', models.CharField(choices=[('idle', 'Aucune'), ('pending', 'En cours'), ('ready', 'Prête'), ('failed', 'Échec')], default='idle', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
