# Generated by Django 5.2.17 on 2026-10-06 17:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_badges_profile_karma_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='availability_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_rate',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='pinned',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_preferences',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='SkillEndorsement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('skill', models.CharField(max_length=30)),
                ('endorsee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements_received', to=settings.AUTH_USER_MODEL)),
                ('endorser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['endorsee', 'skill'], name='profiles_sk_endorse_13bf37_idx')],
                'constraints': [models.UniqueConstraint(fields=('endorsee', 'endorser', 'skill'), name='profiles_one_endorsement')],
            },
        ),
    ]
