# Generated by Django 5.2.17 on 2026-10-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_availability_note_profile_daily_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accent_color',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
