# Generated by Django 5.2.17 on 2026-10-06 17:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('icon', models.CharField(blank=True, max_length=300)),
                ('banner_url', models.URLField(blank=True)),
                ('rules', models.JSONField(blank=True, default=list)),
                ('target_country', models.CharField(blank=True, max_length=60)),
                ('is_verified', models.BooleanField(default=False)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hubs_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HubMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('role', models.CharField(choices=[('member', 'Membre'), ('moderator', 'Modérateur')], default='member', max_length=10)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='hubs.hub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='hub',
            index=models.Index(fields=['-member_count'], name='hubs_hub_member__a06619_idx'),
        ),
        migrations.AddConstraint(
            model_name='hubmembership',
            constraint=models.UniqueConstraint(fields=('hub', 'user'), name='hubs_one_membership'),
        ),
    ]
