# Generated by Django 5.2.17 on 2026-10-04 20:42

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
import uuid
from django.db import migrations, models
from pgvector.django import VectorExtension

HNSW_INDEX = "knowledge_chunk_embedding_hnsw"


def create_hnsw_index(apps, schema_editor):
    # Recherche approchée rapide par distance cosinus ; inutile (et impossible) sous SQLite.
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            f"CREATE INDEX IF NOT EXISTS {HNSW_INDEX} ON knowledge_chunk "
            "USING hnsw (embedding vector_cosine_ops)"
        )


def drop_hnsw_index(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(f"DROP INDEX IF EXISTS {HNSW_INDEX}")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('source_type', models.CharField(choices=[('snippet', 'Snippet'), ('question', 'Question résolue'), ('project', 'Projet')], max_length=20)),
                ('source_id', models.UUIDField()),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_type', 'source_id'), name='knowledge_doc_unique')],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('position', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.document')),
            ],
            options={
                'ordering': ['document', 'position'],
            },
        ),
        migrations.RunPython(create_hnsw_index, drop_hnsw_index),
    ]
