# Generated by Django 5.2.17 on 2026-10-05 20:02

import math
from datetime import UTC, datetime

from django.conf import settings
from django.db import migrations, models

# Copie figée de services.ranks (une migration ne dépend pas du code applicatif).
RANK_EPOCH = datetime(2025, 1, 1, tzinfo=UTC).timestamp()


def backfill(apps, schema_editor):
    """Les anciens « j'aime » deviennent des votes ↑ : score = like_count, puis les rangs."""
    Post = apps.get_model("feed", "Post")
    for post in Post.objects.all().only("id", "like_count", "created_at"):
        seconds = post.created_at.timestamp() - RANK_EPOCH
        score = post.like_count
        sign = (score > 0) - (score < 0)
        hot = round(sign * math.log10(max(abs(score), 1)) + seconds / 45000, 7)
        Post.objects.filter(id=post.id).update(score=score, hot=hot, top=score + seconds / 1e10)


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hot',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='top',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='postlike',
            name='value',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-hot'], name='feed_post_hot_c33005_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-top'], name='feed_post_top_17dd01_idx'),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
