# Generated by Django 5.2.17 on 2026-10-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_post_title_votes_ranks'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hub_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
